---
# RedHat
- name: install zabbix-agent
  yum: name=zabbix-agent state=present disable_gpg_check=yes
  when: ansible_os_family == "RedHat"

# Ubuntu14
- name: install zabbix-agent
  apt: name=zabbix-agent state=present update_cache=yes
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "14"

# Ubuntu12
- name: install zabbix-agent
  apt: name=zabbix-agent state=present update_cache=yes
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "12"

- name: copy proxy configuration
  template: src=zabbix_agentd.conf.j2 dest=/etc/zabbix/zabbix_agentd.conf
  notify: service zabbix-agent
