---
- name: install zabbix-agent
  yum: name=zabbix-agent state=latest disable_gpg_check=yes

- name: copy proxy configuration
  template: src=zabbix_agentd.conf.j2 dest=/etc/zabbix/zabbix_agentd.conf
  notify: service zabbix-agent
