---
# RedHat
- name: install zabbix-agent
  yum: name=zabbix-agent state=present disable_gpg_check=yes
  when: ansible_os_family == "RedHat"

# Ubuntu14 (just agent)
- name: get Ubuntu14 repo
  get_url: url=http://repo.zabbix.com/zabbix/2.4/ubuntu/pool/main/z/zabbix/zabbix-agent_2.4.5-1+trusty_amd64.deb dest=/usr/src/zabbix-agent_2.4.5-1+trusty_amd64.deb
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "14"
  notify: service zabbix-agent

- name: install Ubuntu14 repo
  apt: deb=/usr/src/zabbix-agent_2.4.5-1+trusty_amd64.deb 
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "14"
  notify: service zabbix-agent

# Ubuntu12 (just agent)
- name: get Ubuntu12 repo
  get_url: url=http://repo.zabbix.com/zabbix/2.4/ubuntu/pool/main/z/zabbix/zabbix-agent_2.4.5-1+precise.deb dest=/usr/src/zabbix-agent_2.4.5-1+precise.deb
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "12"
  notify: service zabbix-agent

- name: install Ubuntu12 repo
  apt: deb=/usr/src/zabbix-agent_2.4.5-1+precise.deb 
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "12"
  notify: service zabbix-agent

# Debian Wheezy ARM and Raspbian7 (Raspiberry Pi) (just agent)
- name: get debian wheezy arm repo 
  get_url: url=http://download.jangaraj.com/zabbix/zabbix-agent_2.4.2-1+wheezy_armhf.deb dest=/usr/src/zabbix-agent_2.4.2-1+wheezy_armhf.deb 
  when: ansible_distribution == "Debian" and ansible_distribution_major_version == "7" and ansible_architecture == "armv6l"
  notify: service zabbix-agent

- name: install debian wheezy arm repo
  apt: deb=/usr/src/zabbix-agent_2.4.2-1+wheezy_armhf.deb
  when: ansible_distribution == "Debian" and ansible_distribution_major_version == "7" and ansible_architecture == "armv6l"
  notify: service zabbix-agent

# Template
- name: copy proxy configuration
  template: src=zabbix_agentd.conf.j2 dest=/etc/zabbix/zabbix_agentd.conf
  notify: service zabbix-agent
